group = core
admin-port = 13000
smsbox-port = 13001
dlrdump = /var/log/kannel/dlr.log
log-file = /var/log/kannel/kannel.log

group = smsc
smsc = smpp
smsc-id = mtn_cameroon
host = smpp.mtn.cm
port = 2775
smsc-username = YOUR_SMPP_USER
smsc-password = YOUR_SMPP_PASS
system-type = VMA

group = smsbox
bearerbox-host = localhost
sendsms-port = 13013
group = sendsms-user
user = santeproche
password = APP_SECRET
